---
language: python
services: docker

env:
  global:
    - ROLE_NAME: pdns-recursor
  matrix:
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: debian10
    # - MOLECULE_DISTRO: debian9  # do not work at the moment

install:
  # Install test dependencies.
  - pip install molecule docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-$ROLE_NAME wftech.$ROLE_NAME
  - cd wftech.$ROLE_NAME

script:
  # Run tests.
  - molecule test

notifications:
  webhooks:
    - https://galaxy.ansible.com/api/v1/notifications/
