---
- name: Assert we're on CentOS nodes
  assert:
    that:
      - ansible_distribution == 'CentOS'
      - ansible_distribution_major_version == '7'

- name: Add pdns-recursor
  yum:
    name: pdns-recursor
    state: present
